apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc-server
  template:
    metadata:
      labels:
        app: webrtc-server
    spec:
      containers:
      - name: webrtc-server
        image: younes43/webrtc-server:latest
        ports:
        - containerPort: 9000
